### ISSUE TITLE
QtDeclarative deprecated as of Qt 5.6

### ISSUE THREAD

**Issue by RomanHargrave** [omega-gg/MotionBox#1]
Due to this builds on Qt 5.6+ may require extra work

**Comment by 3unjee** [comment]
That's correct Roman, QtDeclarative (QtQuick 1) is deprecated on Qt 5.6.
That being said it can still be built from the source.

Porting Sky kit to QtQuick 2 is high on my priority list.
In the meantime I recommend Qt 4.8 or Qt 5.5.

**Comment by 3unjee** [comment]
MotionBox 1.4.0 is built on Qt 5.
