### ISSUE TITLE
Latest version 1.5.0 removed playback speed slider

### ISSUE THREAD

**Issue by IntendedConsequence** [omega-gg/MotionBox#12]
Seems to have happened in this commit https://github.com/omega-gg/MotionBox/commit/6ba547b36c646d9e19b16cbb7509504094f4b0fa

**Comment by 3unjee** [comment]
Well it's an intended consequence :). Were you actually using the feature ?

**Comment by IntendedConsequence** [comment]
I can't imagine watching videos without it. If you consider putting it back, might I suggest increasing max speed limit to at least x3?

**Comment by 3unjee** [comment]
Yeah, it might come back in an advanced panel. But I'm quite busy with other things right now.

**Comment by 3unjee** [comment]
The video slider is back in 1.6.0-5: http://omega.gg/t/playback-speed-playrate-button/98/3
