### ISSUE TITLE
A video pretends to have been uploaded 50 years ago

### ISSUE THREAD

**Issue by TheDalaiAlpaca** [omega-gg/MotionBox#14]
I found a video that sais it was uploaded 50 ago. Looking up the URL on YouTube shows that it should actually be '5 years ago'. https://www.youtube.com/watch?v=lucWtN23jsI

**Comment by 3unjee** [comment]
Hi @TheDalaiAlpaca, ahah that's a good one, thank you for reporting.

Can't seem to reproduce on my side, could you "force reinstall" the latest version and let me know (the update notifier is broken on 1.6.0-0).

**Comment by TheDalaiAlpaca** [comment]
Hi. I was already on version 1.6.0 when I posted this.

Before redownloading, I thought it was a good idea to back up ~/.local/share/Motionbox by renaming it. When I then started Motionbox and went to the video, it properly said '5 years ago'.

Then I restored my old ~/local/share/Motionbox directory and started Motionbox. This time the upload date of the video was '439312 hours ago'.

Then I downloaded and installed the latest version from omega.gg. I went to the video and it still said '439312 hours ago'. Then I clicked on the URL and pressed enter to reload it, and the upload date was displayed nicely as '5 years ago'.

So I guess it's just something quirky with my video data directory, which is quite old already.

**Comment by 3unjee** [comment]
Yes, maybe the track was badly retrieved by an old version and then stayed like this in your local playlist.

The current fix would be to remove the track and add it again. But I don't like that very much so I think we should implement a way to reload tracks at one point (even though I like the fact that you can keep information about an old / deleted track to cope with censorship).
