### ISSUE TITLE
Connection behind proxy try to exec /usr/bin/proxy

### ISSUE THREAD

**Issue by Glandos** [omega-gg/MotionBox#16]
I'm using 1.6.0 on Debian/testing behind an HTTP proxy.
Trying to play a Youtube video fails: I can search, show information, but clicking on the play button just load, and then go back to stop mode.
By using strace -f -eexecve, I'm seeing those strange fork:
```strace
[pid 209928] execve("/usr/local/bin/proxy", ["proxy", "https://r1---sn-4g5e6nze.googlev"...], 0x7ffc431daaf8 /* 39 vars */) = -1 ENOENT (Aucun fichier ou dossier de ce type)
[pid 209928] execve("/usr/bin/proxy", ["proxy", "https://r1---sn-4g5e6nze.googlev"...], 0x7ffc431daaf8 /* 39 vars */) = -1 ENOENT (Aucun fichier ou dossier de ce type)
[pid 209928] execve("/bin/proxy", ["proxy", "https://r1---sn-4g5e6nze.googlev"...], 0x7ffc431daaf8 /* 39 vars */) = -1 ENOENT (Aucun fichier ou dossier de ce type)
[pid 209928] execve("/usr/local/games/proxy", ["proxy", "https://r1---sn-4g5e6nze.googlev"...], 0x7ffc431daaf8 /* 39 vars */) = -1 ENOENT (Aucun fichier ou dossier de ce type)
[pid 209928] execve("/usr/games/proxy", ["proxy", "https://r1---sn-4g5e6nze.googlev"...], 0x7ffc431daaf8 /* 39 vars */) = -1 ENOENT (Aucun fichier ou dossier de ce type)
```
I guess that it tries to download the video, but of course `proxy` isn't a valid binary :)

Is there any solution to this?

**Comment by 3unjee** [comment]
Greetings @Glandos,

Have you tried to configure your proxy from the Application panel (upper left corner).

**Comment by Glandos** [comment]
I don't uunderstand what I did, but now, even after deleting `.local/share/MotionBox`, and without environment variables, I'm getting the same behavior... Maybe I'm missing something?

**Comment by 3unjee** [comment]
@Glandos, In MotionBox the procedure would be the following
1. Click on the "application button" (the M blue icon on the upper left corner)
2. Locate the "Proxy" section and click on "configure"
3. Configure the Host, Port, Password, Global / Stream (Global applies the proxy to everything, Stream is just for the video player)
4. Click "Active"
5. Click "OK"

**Comment by Glandos** [comment]
After more test, I think that this behavior is linked to some embedded components, but has nothing to do with my proxy. It's still happening within my home-without-proxy network, and a lot of video (from YouTube) aren't playing.

But clearly, proxy processing isn't involved.
