### ISSUE TITLE
cannot start video, only audio

### ISSUE THREAD

**Issue by hrotkogabor** [omega-gg/MotionBox#19]
I am using motionbox 1.6.0.4-3 on manjaro from AUR. My problem is that I cannot start any video. The cover is displayed, but when I click the play, it will try to start, but then stop. If I switch to audio only, it will play the audio fine.
I made an strace output of this.
[motionboxStrace.txt](https://github.com/omega-gg/MotionBox/files/4682851/motionboxStrace.txt)

**Comment by 3unjee** [comment]
@hrotkogabor Oh, can you confirm it does that on every backend or just Youtube ? Also is it every video or just a few ?

**Comment by hrotkogabor** [comment]
I just tested it with more videos, and the result is the same.
With dailymotion it is the same. With Vimeo and Bittorent, the video is playing without video, only sound.
Is there any way to debug it further?

**Comment by 3unjee** [comment]
That's probably an issue on the rendering side. When playing the video do you see a black screen?

**Comment by hrotkogabor** [comment]
yes, this is black

**Comment by 3unjee** [comment]
Well I would have to test it on Manjaro, currently the build is tested with Ubuntu.

If you have any knowledge in programming you could try to build the latest version of MotionBox and investigate the rendering part. Have you got another distribution to test on?

**Comment by 3unjee** [comment]
Have you tried to switch from video to audio in the settings panel (lower right corner) ?

**Comment by hrotkogabor** [comment]
In virtualbox with manjaro it is the same. When I switch to audio on vimeo, I see the cover, with audio playing. With video, it is black while playing the video.
I will try to experiment with the code, but I am not very familiar with C++.

**Comment by G-P-L** [comment]
Hi @3unjee !

I am currently investigating this issue. Video won't start, just audio is playing when using any backend. No error messages are printed in the console, so I think this is a VLC or other dependency issue. I will try to downgrade the packages to test this idea.

**Comment by 3unjee** [comment]
So it seems to be an issue on Arch Linux no matter the distribution, I've recently added the VLC libraries in the archive, maybe Arch doesn't like it. You could try remove libVLC and the vlc folder from the installation path.

**Comment by G-P-L** [comment]
Yes, it is definietly an Arch-related issue, but I could solve it now based on your suggestion. If I just removed the vlc folder and the libvlc.so.5 library, the MotionBox simply did not start. Instead, if I created a symlink from the system vlc library and vlc folder to the MotionBox folder, the issue disappeared.
I will update the Arch AUR package to include this solution today.

**Comment by G-P-L** [comment]
So, thanks for the help again!

**Comment by 3unjee** [comment]
That's weird we shouldn't have to do that, since by default MotionBox should use the system VLC, I'm a bit confused about the exact reason. Are you running the app with start.sh?

**Comment by G-P-L** [comment]
Yes, I am using the start.sh always (or in rare cases I am manually setting the LD_LIBRARY_PATH when testing something, but it is doing the same).

Anyway, the AUR package updated with the symlinking workaround. Version 1.6.0.4-4 fix this issue for the Arch users.

If I just remove the VLC files, the MotionBox windows is appearing for a second then closes and I will get the following ouput in terminal:
vlc: unknown option or missing mandatory argument --http-reconnect
Try vlc --help for more information.
WVlcEngine::event: Cannot create VLC instance. Is VLC installed ?
./start.sh: 11. sor: 558784 Félbeszakítva         (core készült) "$PWD/MotionBox"

**Comment by hrotkogabor** [comment]
Updating with pamac-manager gui will result this, even after click empty aur cache:

Telepítés motionbox...
==> Csomag készítése: motionbox 1.6.0.4-4 (2020. jún. 2., kedd, 08:51:41 CEST)
==> Futtatási függőségek ellenőrzése...
==> Fordítási függőségek ellenőrzése...
==> Források letöltése...
  -> MotionBox-1.6.0-linux64.tar.gz helyi forrás
  -> MotionBox.desktop helyi forrás
  -> MotionBox.png helyi forrás
==> source fájl eredetiségének ellenőrzése ezzel: sha256sums...
    MotionBox-1.6.0-linux64.tar.gz ... HIBA
    MotionBox.desktop ... Rendben
    MotionBox.png ... Rendben
==> HIBA: Egy vagy több fájl nem ment át az eredetiségellenőrzésen!
Nem sikerült összerakni: motionbox

It says MotionBox-1.6.0-linux64.tar.gz is a local file, and sha256sums failed.
Updating from cli with yay, just re downloaded it, and install successfully.
I tested it, and it works now.
So I think, this issue can be closed.
Thank you guys!
