### ISSUE TITLE
need libicui18n.co

### ISSUE THREAD

**Issue by Kwaskoff** [omega-gg/MotionBox#21]
get http://omega.gg/get/MotionBox/MotionBox-1.6.0-linux64.tar.gz
unzip and start
it's need  libicui18n.co
ok, I installed  libicui-dev
nothing
____
xubuntu 20.04

**Comment by 3unjee** [comment]
Thank you for reporting it, I'll investigate the issue ASAP.

**Comment by 3unjee** [comment]
Have you started the program using `sh start.sh` ?
