### ISSUE TITLE
Youtube videos do not unpause when program is left idle for a while.

### ISSUE THREAD

**Issue by BackThrowTheBaguetteBrawler** [omega-gg/MotionBox#28]
Steps to Reproduce:
Open youtube video.
Pause somewhere in the video.
Leave computer on overnight (probably doesn't need to be nearly that long)
Try to unpause the video.

Fedora Linux 32
AMD Opteron 6320 2.8ghz
Radeon HD 7770
128gb DDR3 1600

**Comment by 3unjee** [comment]
Thank you for reporting, this is probably related to the validity timeout of a video source on the Youtube backend. I'll take a look.

**Comment by 3unjee** [comment]
This should be fixed with MotionBox 1.6.0-10 and this: https://github.com/omega-gg/backend/commit/975e63f2f797a355070118157c42fc5a764801af

**Comment by 3unjee** [comment]
@BackThrowTheBaguetteBrawler could you confirm it's fixed on your side ? Thanks

**Comment by BackThrowTheBaguetteBrawler** [comment]
yes! it is fixed. thanks!
