### ISSUE TITLE
qt4 This PPA does not support xenial

### ISSUE THREAD

**Issue by philena** [omega-gg/MotionBox#29]
**~/Downloads/MotionBox $** sh 3rdparty.sh linux all
CLEANING

Reading package lists... Done
Building dependency tree       
Reading state information... Done
'
'
...
INSTALLING Qt4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (1.7.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
_'This PPA does not support xenial'
Cannot add PPA: ''This PPA does not support xenial''._

**~/Downloads/MotionBox $** sudo add-apt-repository ppa:rock-core/qt4
_'This PPA does not support xenial'
Cannot add PPA: ''This PPA does not support xenial''._

System info 
Kernel: 4.15.0-128-generic 
LInux Mint 18.3 Cinnamon 64-bit (3.6.7)

**Comment by 3unjee** [comment]
@philena could you type `cat /etc/os-release` and let me know the result ?

**Comment by philena** [comment]
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial

**Comment by 3unjee** [comment]
Thanks, it should be fixed by now: https://github.com/omega-gg/3rdparty/commit/d59296efd1dc3c8d09caf94b83dfd6f5f4a41404
