### ISSUE TITLE
Can't move to other monitor

### ISSUE THREAD

**Issue by tudoanh** [omega-gg/MotionBox#31]
I'm using Ubuntu 20.04 with MotionBox 1.6.0-12, and I can't move the window to my second monitor. Can you fix that?

Awesome project btw

**Comment by 3unjee** [comment]
That's something I cannot easily reproduce via a VirtualBox unfortunately.  Could you give me more details about what's happening ?

Thank you for using MB.

**Comment by tudoanh** [comment]
Oh I got it, turn out my main monitor have 2K resolution and the other is just 1080p. And the MotionBox window is just too big to move to the 2nd monitor.
