### ISSUE TITLE
Little Ergonomic Improvement 

### ISSUE THREAD

**Issue by JayBeeDe** [omega-gg/MotionBox#32]
MotionBox is a wonderful project, thank you for that!
MotionBox uses its own window theme and it's probably what makes its design amazing.
Nevertheless, it would be better to move the minimize, restore and close buttons to the very top right so that it's consistent with other windows, especially when user wants to close all its windows. Affecting at least Windows and Ubuntu, probably all OS.
To summarize the ergonomic improvement:
![Sélection_018](https://user-images.githubusercontent.com/17429937/114300080-d13f9180-9abe-11eb-9c26-28b889509550.png)

**Comment by 3unjee** [comment]
Greetings @JayBeeDe and thank you for your feedback.

The initial reasoning behind that was to leave a space for the user to resize the window diagonally. But I'm not so sure it's relevant, I guess I could try that fix and we'll see how it goes.

**Comment by 3unjee** [comment]
This is fixed on the current master. Enjoy.

**Comment by JayBeeDe** [comment]
Thank you very much

**Comment by jonas-w** [comment]
May i ask how you made motionbox dark?

**Comment by 3unjee** [comment]
@jonas-w Lower right corner > Settings > Application > Night.

**Comment by jonas-w** [comment]
OOOOH I've wondered why there were such few settings. Now i realize it xd thank you

**Comment by 3unjee** [comment]
I'll admit the UI on this is not excellent unfortunately.
