### ISSUE TITLE
[Bug?] Player does not prevent monitor from getting switched off in Arch Linux

### ISSUE THREAD

**Issue by DanteIgashu** [omega-gg/MotionBox#37]
Hello! 😄
In Arch Linux, using Kernel 5.12.9-arch1-1 (64 bit), and KDE Plasma 5.22.0 with QT version 5.82.0, and Motionbox 1.7.0.0, the player does not prevent the monitor from getting switched off (power save configuration set to 5 minutes), so I have to be moving the mouse or pressing a key every once in a while to prevent that from happening.
I am guessing it is just a missing instruction in the configuration file, maybe?
THANKS in advance and great app, I like it! 😄

**Comment by 3unjee** [comment]
Thanks for reporting this, that's actually an issue. I'll look into it.

**Comment by 3unjee** [comment]
Have you got the same issue when going into fullscreen ?

**Comment by DanteIgashu** [comment]
> Have you got the same issue when going into fullscreen ?

Yes, I did, I even checked on Windows just to be sure that it wasn't a general issue, but no, it just happens on linux. I also noticed other issue on linux, but I guess I will open a new report for that one, but before that, I am gonna check on another computer just to be sure and also have a better idea of what's happening.
THANKS for the reply! : D

**Comment by 3unjee** [comment]
Could you try one of these artifacts: https://dev.azure.com/bunjee/MotionBox/_build/results?buildId=3231&view=artifacts&pathAsName=false&type=publishedArtifacts ?

**Comment by DanteIgashu** [comment]
> Could you try one of these artifacts: https://dev.azure.com/bunjee/MotionBox/_build/results?buildId=3231&view=artifacts&pathAsName=false&type=publishedArtifacts ?

Done, I tried "MotionBox-linux64-qt5", I was able to try the "normal" and "full" screen modes, and the problem seems to be gone in the "artifact" version. Was gonna try all the screen modes, but, for a reason or reasons I ignore, after using the "artifact" version, none, neither my installed MotionBox software, nor the "artifact" are able to load anything, they just get stuck in the loading step. I don't know if that's expected at the moment, but I even erased the /.local/shared/MotionBox folder (something both versions of the software use) and none of them still worked.
But the Monitor doesn't get switched off anymore. THANKS!

Note: Gonna try uninstalling the software and reinstalling to see if it works again.

**Comment by 3unjee** [comment]
>  they just get stuck in the loading step. I don't know if that's expected at the moment, but I even erased the /.local/shared/MotionBox folder

That shouldn't happen, especially if you remove the `/.local/shared/MotionBox` folder. Pay attention that doing so might remove your playlists too, so you might want to backup them first. In the future I'll add some way to export them.
