### ISSUE TITLE
error while loading shared libraries: libvlc.so.5

### ISSUE THREAD

**Issue by amfogor** [omega-gg/MotionBox#39]
I downloaded `MotionBox-1.8.0-0-linux64.tar.gz`, ran `./MotionBox`, and got the following error

> ./MotionBox: error while loading shared libraries: libvlc.so.5: cannot open shared object file: No such file or directory

**Comment by 3unjee** [comment]
You need to have VLC installed on your system, is it the case ?

**Comment by amfogor** [comment]
@3unjee why would that be requirement? Just ship it as all the other dependencies.

**Comment by 3unjee** [comment]
I tried to do this at some point on Linux but gave up based on the daunting task it represents. libVLC has *many* dependencies.

**Comment by amfogor** [comment]
Can't it be automated? Like recursively list all the dependencies by parsing ELF and looking at the dynamic table (like `readelf -d` does)

**Comment by 3unjee** [comment]
Yeah probably ? Or an AppImage would be cool too. 

Feel free to contribute on that part if you like the program.

**Comment by amfogor** [comment]
I'll consider when I'll switch from Gentoo to Guix. Right now I can't even install VLC.

**Comment by 3unjee** [comment]
The latest version is AppImage based and should run without problem. Let me know.
