### ISSUE TITLE
[QUESTION] Is there any way to enable hardware acceleration?

### ISSUE THREAD

**Issue by AndGuz** [omega-gg/MotionBox#40]
I ask because if i put the video quality to more than 1080p it lags on my laptop, and as i know you use vlc internally it could be possible to enable it. Also, vlc works flawlessly on this same machine, thanks in advance for your answer :)

**Comment by AndGuz** [comment]
I saw that in the Sky Kit `--hw-codec=any` was commented out, maybe it could possibly be because of that

**Comment by AndGuz** [comment]
![imagen](https://user-images.githubusercontent.com/62262763/172060117-55db4f7e-0767-4b55-96ca-819a668ab8dc.png)
As this image says, its not using the video capabilities of the iGPU, as far i know vlc can use them. Sorry for my bad english and thanks for this awesome piece of software.

**Comment by 3unjee** [comment]
That's very weird, by default hardware decoding should be enabled on libVLC side.

**Comment by AndGuz** [comment]
Yeah, i tested on windows and is the same.

**Comment by 3unjee** [comment]
Well, trying with or without `--avcodec-hw=any` does not seem to affect video decoding performances on my side.

**Comment by AndGuz** [comment]
Maybe is a libVLC thing or bug

**Comment by AndGuz** [comment]
Yes, it is. Or maybe is my PC hehehe, thanks bro for your response

**Comment by AndGuz** [comment]
I figured out that this issue could be because some Intel processors can't decode AV1/VP8/VP9 video, so I'm gonna close the issue. Thanks for this awesome software :)
