### ISSUE TITLE
Sections of the display window are not properly showing, arranging, or scaling

### ISSUE THREAD

**Issue by UntypedLetter** [omega-gg/MotionBox#49]
<img width="401" alt="MotionBox display issue" src="https://github.com/omega-gg/MotionBox/assets/145196151/a997f1bf-b2cb-4bdb-ad80-2de1fc592b15">
<img width="960" alt="MotionBox display issue 2" src="https://github.com/omega-gg/MotionBox/assets/145196151/7a603036-ed65-49ef-a6f8-752ebe9db9f5">

As the screenshots show, even maximizing the window doesn't help.

**Comment by 3unjee** [comment]
You mean your interface is cropped ? Which platform are you on ?

**Comment by UntypedLetter** [comment]
I'm on Windows 10. I tried both the portable version of MotionBox as well
as the installer version, but this "cropped" interface problem is
experienced in both.

**Comment by 3unjee** [comment]
That's very uncommon, can you try to set Windows scaling on 100% and run the application again ?

**Comment by UntypedLetter** [comment]
I set the Windows scaling to 100%, but the problem still persists. Didn't
seem to make any difference to the display interface. Still cropped.

**Comment by UntypedLetter** [comment]
Motion Monkey (portable) also displaying a cropped interface on my machine.

**Comment by 3unjee** [comment]
Yeah, at this point I'd almost need your machine to investigate. Are you in a position to build HelloSky / MotionBox ?

**Comment by UntypedLetter** [comment]
Ha, ha.

Can't build, so sorry.
All I can tell you is that once I was having some kind of scaling problem
with another app (probably VLC ) and I had to add two Quick Time
environment variables:

Variable name: QT_AUTO_SCREEN_SCALE_FACTOR
Variable value: 0

Variable name: QT_SCREEN_SCALE_FACTORS
Variable value: 1.5

This solved the problem for that app. Could this be interfering?

**Comment by 3unjee** [comment]
QT_SCREEN_SCALE_FACTORS=1.5 is the culprit.

Will be fixed by: https://github.com/omega-gg/Sky/commit/a984881fce2070363c5252227a826d6a71379fa6

**Comment by UntypedLetter** [comment]
That's great, Benjamin! :-)

So what do I do now? Download something, or wait for the next release, or
what?

**Comment by 3unjee** [comment]
Change your env QT_SCREEN_SCALE_FACTORS to 1 or wait for the next MB / Monkey releases.

**Comment by UntypedLetter** [comment]
Yes, problem solved.

Thank you so much for coding these excellent apps! :-)
