### ISSUE TITLE
[Suggestion]: Pop-out player

### ISSUE THREAD

**Issue by GleammerRay** [omega-gg/MotionBox#50]
Hello!

MotionBox is a great and a pretty versatile program, but it does lack an always on top pop-out video player (unless it is already feature and I have simply missed it). It would be nice to have that as it is a core feature of most modern video platforms. It would also eliminate the need for me to use MotionMonkey with MotionBox installed, as I'm only using MotionMonkey for its ability to play videos in a tiny window.

**Comment by 3unjee** [comment]
Hi @GleammerRay, you have the "Stay on top" option in the cog then "Player" and then "Advanced".

Although there's no way to get completely rid of the UI in MotionBox unless you're in full screen. For such behavior I'd recommend MotionMonkey.
